---
# GamemodeUI plugin
# Made By FlynnKunz

##############################

# Use "§" as formatting codes
# Use "\n" to break into new line

title: "§e§lGamemode Menu"
# Set The Title

content: "§eSelect Gamemode"
#Set The Content

---
