---
# GamemodeUI plugin
# Made By FlynnKunz

##############################

# Use "ยง" as formatting codes
# Use "\n" to break into new line

title: "Change in config.yml"
# Set The Title

content: "Change in config.yml"
#Set The Content

---
