---
  # GamemodeUI plugin
  # Made By FlynnKunz , ItzBluee02
  # Pliss Subscribe My Ch ItzBluee02

  ##############################

  # Use "§" as formatting colors
  # Use "\n" to break into new line
  # ======(PREFIX)======
  Prefix: "§l§7[§eGM§7]§8»§r"
  # ======(MESSAGES FORMS)======
  GamemodeUI:
    # Set The Title
    title: "§l§0BLUEE GMDUI"
    # Set The Content
    content: "§ePilih Salah Satu Di Bawah:"
    # Buttons
    button-survival: "§8§lSurvival\n§r§0Tap To Change"
    button-creative: "§8§lCreative\n§r§0Tap To Change"
    button-adventure: "§8§lAdventure\n§r§0Tap To Change"
    button-spectator: "§8§lSpectator\n§r§0Tap To Change"
    button-exit: "§4§lEXIT§r\n§r§0Tap To Change"
  # Message To Players Change Gamemode
  Messages:
    survival: "§bYour game mode has been changed to §dSURVIVAL"
    creative: "§bYour game mode has been changed to §dCREATIVE"
    adventure: "§bYour game mode has been changed to §dADVENTURE"
    spectator: "§bYour game mode has been changed to §dSPECTATOR"
  # Message To Players Not Have Permissions
  NoPermissionMessages:
  survival: "Â§cYou Dont Have Permission To Use This Commands"
  creative: "Â§cYou Dont Have Permission To Use This Commands"
  adventure: "Â§cYou Dont Have Permission To Use This Commands"
  spectator: "Â§cYou Dont Have Permission To Use This Commands"
---
